#pragma once

enum RENDER_TARGET_ID
{
    RT_FP16,
    RT_GBUFFER_ALBEDO,
    RT_GBUFFER_NORMAL,
    RT_GBUFFER_METALL_ROUGHNESS,
    RT_GBUFFER_WORLD_POS, //tmp
    RT_SSAO_MASK,
    RT_SSAO_MASK_BLENDED,
    RT_SHADOW_MAP,
    RT_DEPTH_BUFFER,
    RT_BACK_BUFFER,
    RT_LAST
};

static const char* RENDER_TARGET_NAME[] = {
    "FP16",
    "GBUFFER_ALBEDO",
    "GBUFFER_NORMAL",
    "GBUFFER_METALL_ROUGHNESS",
    "GBUFFER_WORLD_POS",
    "SSAO_MASK",
    "SSAO_MASK_BLENDED",
    "SHADOW_MAP",
    "DEPTH_BUFFER",
    "BACK_BUFFER",
    "LAST"
};
